function init_fem()
NODES=6;
ELEMENTS=4;
COMPONENTS=3;
NODES_TRIA3 = 3;
DOF_NODE=2;
DOF_TOTAL=DOF_NODE*NODES;
DOF_TRIA3 = DOF_NODE*NODES_TRIA3;
THICKNESS =  1;
YOUNG = 210000;
POISSON = 0.3;

x = [];
y = [];
connectivity = zeros(ELEMENTS,NODES_TRIA3);

end